### ISSUE TITLE
[BUG 🐞]: App crashes on clicking delete Trash icon

### ISSUE THREAD

**Issue by warmachine028** [SrijaAdhya12/Expense-App#1]
## Description:
- App crashes to `Method not Allowed` page when clicked trash icon in view details page

## Steps to reproduce the bug:
1. Create a user
2. Create Budget
3. Add item to the budget by entering new expense
4. Click view details
5. From the Expenses list click the red trash icon beside a particular expense

## Evidence:
![Bug](https://github.com/SrijaAdhya12/Expense-App/assets/75939390/3b329c64-40b0-4e7f-8670-a0ed626e7578)

**Comment by SrijaAdhya12** [comment]
closed as solved.

**Comment by SrijaAdhya12** [comment]
closed as solved.
